// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwR-tlCiwx72f1YeGEjOEGJQcpuwXrNk',
    appId: '1:988598383985:web:e591e966cc1538e99bb2d0',
    messagingSenderId: '988598383985',
    projectId: 'fly-savvy',
    authDomain: 'fly-savvy.firebaseapp.com',
    storageBucket: 'fly-savvy.appspot.com',
    measurementId: 'G-W095XTXYYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNxOd5soWRRaKGTYtZju1S0gQugf7ZHD0',
    appId: '1:988598383985:android:ae52313f5dfb9f0d9bb2d0',
    messagingSenderId: '988598383985',
    projectId: 'fly-savvy',
    storageBucket: 'fly-savvy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSt3dc045DWXmv94mxv6AnBxxuB53IWN4',
    appId: '1:988598383985:ios:65cb19335f2901c99bb2d0',
    messagingSenderId: '988598383985',
    projectId: 'fly-savvy',
    storageBucket: 'fly-savvy.appspot.com',
    androidClientId: '988598383985-5d39uk7lajr0ptcb9grsikm5avjeh3lp.apps.googleusercontent.com',
    iosClientId: '988598383985-br6atjhjbbj08k63m90io9usnkaqmhvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightSavvy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSt3dc045DWXmv94mxv6AnBxxuB53IWN4',
    appId: '1:988598383985:ios:2989995b6fb7ffe89bb2d0',
    messagingSenderId: '988598383985',
    projectId: 'fly-savvy',
    storageBucket: 'fly-savvy.appspot.com',
    androidClientId: '988598383985-5d39uk7lajr0ptcb9grsikm5avjeh3lp.apps.googleusercontent.com',
    iosClientId: '988598383985-qr44jsr1hdp2u5ha6tp5vv0otl72g6sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightSavvy.RunnerTests',
  );
}
